// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY0x5q0_3UbQ9-CbLcrgZdu3dKnmLcXj0',
    appId: '1:330431582490:web:39c5d39b1f6d2d5d545ca3',
    messagingSenderId: '330431582490',
    projectId: 'aura-90d09',
    authDomain: 'aura-90d09.firebaseapp.com',
    storageBucket: 'aura-90d09.appspot.com',
    measurementId: 'G-BK147B6PRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEg0b5GNn6X2I82alVyHJdBCr0MJLdhjA',
    appId: '1:330431582490:android:ed8fbc200df4e107545ca3',
    messagingSenderId: '330431582490',
    projectId: 'aura-90d09',
    storageBucket: 'aura-90d09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo69H3_0snIMvI7sIXT8cdwxOxmH9fKug',
    appId: '1:330431582490:ios:54dff50fd7fe39e6545ca3',
    messagingSenderId: '330431582490',
    projectId: 'aura-90d09',
    storageBucket: 'aura-90d09.appspot.com',
    iosBundleId: 'com.example.aura',
  );

}